probin_search/core/urls.py
from django.urls import path
from .views import PersonListView,PersonListTable, PersonDetailView, SearchResultView

app_name = 'person'
urlpatterns = [
    path('', PersonListView.as_view(), name='index'),
    path('list/', PersonListTable.as_view(), name='list-table'),
    

    path("<int:pk>/", PersonDetailView.as_view(), name='person-detail'),
    path("search/", SearchResultView.as_view(), name='search'),
]

probin_search/pages/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='pages-index'),
]

probin_search/probin_search/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = "মিত্র ফাউন্ডেশন । প্রবীণ"
admin.site.site_title = "মিত্র ফাউন্ডেশন । প্রবীণ"
admin.site.index_title = "মিত্র ফাউন্ডেশন । একটি স্বেচ্ছাসেবী সমাজকল্যাণ মূলক প্রতিষ্ঠান "


urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),
    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

probin_search/core/models.py
from django.db import models
from django_resized import ResizedImageField


class Person(models.Model):
    
    MOBILE_BANKING = (
        ('bkash', 'বিকাশ'),
        ('nagad', 'নগদ'),
    )
    
    
    form_number = models.CharField(max_length=8, null=True, blank=True)
    name = models.CharField(max_length=89)
    house_number = models.CharField(max_length=21, null=True, blank=True)
    birth_date = models.DateField(auto_now_add=False, null=True, blank=True)
    age = models.CharField(max_length=89)
    nid_number = models.CharField(max_length=89)
    mobile_number = models.CharField(max_length=89)
    mobile_banking = models.CharField(max_length=89, choices=MOBILE_BANKING ,null=True, blank=True)
    
    father_name = models.CharField(max_length=89, blank=True, null=True) 
    current_address = models.TextField(blank=True, null=True)
    permanent_address = models.TextField(blank=True, null=True)
    birth_place = models.CharField(max_length=89, blank=True, null=True, default='এখন ও যুক্ত করা হয় নাই')
    
    occupassion = models.CharField(max_length=89, blank=True, null=True)
    illness = models.CharField(max_length=89, blank=True, null=True)
    religion = models.CharField(max_length=55, blank=True, null=True)
    child_count = models.CharField(max_length=89, blank=True, null=True)
    living = models.CharField(max_length=144, blank=True, null=True)
    image = ResizedImageField(size=[640, 480], upload_to = 'old/resized/', blank=True, null=True)

    def __str__(self):
        return self.name

probin_search/pages/models.py
from django.db import models

# Create your models here.

probin_search/core/views.py
from .models import Person
from django.views.generic import ListView, DetailView, CreateView
from django.db.models import Q
import re

# Provide list
class PersonListTable(ListView):
    model = Person
    template_name = 'core/list_table.html'
    

# Create your views here.
class PersonListView(ListView):
    model = Person


class PersonDetailView(DetailView):
    model = Person


class SearchResultView(ListView):
    model = Person
    template_name = 'person/search_result.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        value = query.strip()
        print(value);
        
        object_list = Person.objects.filter(
            Q(name__icontains=value) | Q(father_name__icontains=value) |
            Q(nid_number__icontains=value) | Q(age__icontains=value) |
            Q(current_address__icontains=value) | Q(permanent_address__icontains=value) |
            Q(mobile_number__icontains=value) | Q(occupassion__icontains=value)
        )

        return object_list

probin_search/pages/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'pages/index.html')

probin_search/templates/core/list_table.html
{% extends 'master.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
    
        <table class="table table-bordered">
            <thead>
                <tr class="text-center">
                <th scope="col">#</th>
                {% comment %} <th scope="col">ছবি</th> {% endcomment %}
                <th scope="col">নাম</th>
                <th scope="col">পিতার নাম</th>
                <th scope="col">বর্তমান ঠিকানা</th>
                <th scope="col">বয়স</th>
                <th scope="col">NID নম্বর</th>
                <th scope="col">মোবাইল নম্বর</th>
                </tr>
            </thead>
            {% for person in object_list %}
            <tbody>
                <tr class="text-center">
                <th scope="row">{{person.id}}</th>
                {% comment %} <th scope="row"> <img style='height: 21%; width:21%;' class='img-responsive' src="{{person.image.url}}" class="img-rounded" alt={{person.image}} > </th> {% endcomment %}

                <td>{{person.name}}</td>
                <td>{{person.father_name}}</td>
                <td>{{person.current_address}}</td>
                <td>{{person.age}}</td>
                <td>{{person.nid_number}}</td>

                <td>+880 {{person.mobile_number}}</td>

                </tr>
            </tbody>
            {% empty %}
            {% endfor %}
        </table>
    </div>
</div>


{% endblock content %}

probin_search/templates/core/person_detail.html
{% extends 'master.html' %}
{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4 col-sm-4">
            <div class="text-right justify-content-center">
                <img class="card-img-top mx-auto d-block" src={{person.image.url}} alt="{{person.name}}" style="width:55%" width="21rem" height="89%">
            </div>
            <br>
        </div>
        <div class="col-md-8">
            <div class="">
                <div class="text-center mt-3">
                    <h3>{{person.name}}</h3> <hr class="text-primary">
                </div>
                <div class="mb-0">
                    <p style='font-size: 1.3rem'>পিতার নাম : {{person.father_name}}</p>
                </div>
                <div class="row mt-3">
                    <div class="col-sm-6 col-md-6">
                        বয়স : {{person.age}}
                    </div>
                    <div class="col-sm-6 col-md-6">
                        জাতীয় পরিচয় পত্র : {{person.nid_number}}
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-sm-6">
                        বর্তমান ঠিকানা : {{person.current_address}}
                    </div>
                    <div class="col-sm-6">
                        স্থায়ী ঠিকানা : {{person.permanent_address}}
                    </div>
                </div>

                <div class="row mt-3">
                    <div class="col-sm-6">
                        পেশা : {{person.occupassion}}
                    </div>
                    <div class="col-sm-6">
                        অসুস্থতা : {{person.illness}}
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-sm-6">
                        ধর্ম : {{person.religion}}
                    </div>
                    <div class="col-sm-6">
                        সন্তানের সংখ্যা : {{person.child_count}}
                    </div>
                </div>

                <div class="row justify-content-center mt-3">
                    <div class="col-sm-6">
                        মোবাইল নম্বর: <a href="tel:0{{person.mobile_number}}">+880 {{person.mobile_number}}</a>
                    </div>

                    <div class="col-sm-6">
                        ব্যাংক:
                    </div>
                </div>
                <div class="row justify-content-center mt-3">
                    <div class="col-md-6">
                        জন্ম স্থান : {{person.birth_place}}
                    </div>
                    <div class="col-md-6">
                        বসবাস : {{person.living}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

probin_search/templates/core/person_list.html
{% extends 'master.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
    {% for person in object_list %}
        <div class="col-md-4 col-sm-4">
            <a href="{% url 'person:person-detail' person.id%}" style="text-decoration:none">
                <div class="card shadow" style="" >
                    <img class="card-img-top" src={{person.image.url}} alt="{{person.name}}" style="width:100%" width="21rem" height="377rem">
                    <div class="card-body">
                        <h4 class="card-title text-dark text-center font-weight-bolder" style="font-size: 13pt; margin-top: -5pt; margin-bottom: -1pt"> {{person.name}}</h4>
                        <h4 class="card-text text-dark text-center font-weight-bold" style="font-size: 11pt; margin-bottom: -13pt;">+880 {{person.mobile_number}}</h4>
                    </div>
                </div>
            </a>
            <br>
        </div>
    {% empty %}
        <div class="jumbotron bg-secondary text-white">
            <h3>No Person Found !</h3>
        </div>
    {% endfor %}

        {% comment %} <div class="pagination mb-5">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a class='' href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a class='' href="?page={{ page_obj.next_page_number }}">next</a>
                    <a class='' href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>            {% endcomment %}
    </div>
</div>


{% endblock content %}

probin_search/templates/core/search_result.html
{% extends 'master.html' %}
{% block content %}

    <div class="container">
    <div class="row justify-content-center">
    {% for person in object_list %}
        <div class="col-md-4 col-sm-4">
            <a href="{% url 'person:person-detail' person.id%}" style="text-decoration:none">
                <div class="card shadow" style="" >
                    <img class="card-img-top" src={{person.image.url}} alt="{{person.style_name}}" style="width:100%" width="21rem" height="233rem">
                    <div class="card-body">
                        <h4 class="card-title font-weight-bolder text-dark" style="font-size: 13pt; margin-top: -5pt;">{{person.style_name}}</h4>
                        <p class="card-text text-dark" style="font-size: 13pt; margin-top: -5pt;">{{person.composition}}</p>
                    </div>
                </div>
            </a>
        </div>
    {% empty %}
        <div class="jumbotron text-center">
            No person found
        </div>
    {% endfor %}
    </div>
</div>


{% endblock content %}

probin_search/templates/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+Bengali:wght@300&display=swap" rel="stylesheet">
    
    <title>মিত্র । প্রবীণ</title>
</head>
<body style="font-family: 'Noto Serif Bengali', 'Times New Roman';">
    {% include 'navbar.html' %}
    {% block content %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

probin_search/templates/navbar-root.html
<div class="card shadow mb-3" style="border-radius: 0px;">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-white  mt-1">
            <a class="navbar-brand font-weight-bolder" href="{% url 'pages-index' %}"><span style="font-weight: bold; font-size:">মিত্র</span> ফাউন্ডেশন</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" 
                id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto ml-3">
                    <li class="nav-item">
                        <a class="nav-link"
                            href="#">
                            <strong>আমাদের সম্পর্কে</strong>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" 
                            href="{% url 'person:index' %}">
                            <strong>মিত্র প্রবীণ</strong>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"
                            href="#">
                            <strong>আমাদের কার্যক্রম</strong>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"
                            href="#">
                            <strong>আমাদের গঠনতন্ত্র</strong>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"
                            href="#">
                            <strong>ভবিষ্যৎ পরিকল্পনা</strong>
                        </a>
                    </li>
                    
                </ul>
            </div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="container d-flex justify-content-end">
                    <a class='mr-2' href="#" style="text-decoration: none;"><i style="font-size: 21px; color: '#4169e1';" class="fa fa-facebook-official" aria-hidden="true"></i></a>
                    <a class='mr-2' href="#" style="text-decoration: none;"><i style="font-size: 21px; color: '#4169e1';" class="fa fa-youtube-play" aria-hidden="true"></i></a>
                    <a class='mr-2' href="#" style="text-decoration: none;"><i style="font-size: 21px; color: '#4169e1';" class="fa fa-twitter-square" aria-hidden="true"></i></a>
                </div>
            </div>
        </nav>
    </div>
</div>

probin_search/templates/navbar.html
<div class="card shadow mb-3" style="border-radius: 0px;">
    <nav class="navbar navbar-expand-lg navbar-light bg-white mb-2 mt-2">
        <a class="navbar-brand" href="{% url 'pages-index' %}">মিত্র । প্রবীণ</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" 
            id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto ml-3">
                <li class="nav-item">
                    <a class="nav-link" 
                        href="{% url 'person:index' %}">
                        <strong>তালিকা</strong>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                        href="/admin">
                        <strong>অ্যাডমিন</strong>
                    </a>
                </li>
            </ul>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="container d-flex justify-content-end">
                <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'person:search' %}">
                    <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
                </form> 
            </div>
        </div>
    </nav>
</div>

probin_search/templates/pages/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+Bengali:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.maateen.me/kalpurush/font.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>মিত্র ফাউন্ডেশন । একটি স্বেচ্ছাসেবী সমাজকল্যাণ মূলক প্রতিষ্ঠান</title>
    <link rel="stylesheet" href="{% static 'css/core.css' %}">
  </head>

<body style="font-family: 'Kalpurush', 'Noto Serif Bengali', 'Times New Roman';">
    
    {% include 'navbar-root.html' %}
    
    <div class="container ">
        <div class="jumbotron hero-main text-white" style="border-radius: 0%;">
            <div class="container p-5">
                <h2 class="text-center font-weight-bolder ">মিত্র ফাউন্ডেশন</h2><hr>
                <div class="row justify-content-center">
                    <div class="col-md-6">
                        <div class="">
                            <h4 class="text-center">মিক সোয়েটার লিঃ এবং মিক সোয়েটার এন্ড ফ্যাশনস লিঃ এর একটি সামাজিক, স্বেচ্ছাসেবী, সমাজকল্যাণ মূলক প্রতিষ্ঠান ।</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class='container'>
        <h3>আমাদের কার্যক্রম</h3>
        <div class="row">
            <div class="col-md-6">
                <div class="" style='text-align:justify;'>
                    <h5>মিত্র ফাউন্ডেশন এর জন্মলগ্ন থেকে কেবল মানুষের সেবায় নিয়োজিত থেকেছে। বিভিন্ন সামাজিক উন্নয়নমূলক কাজে মিত্র ফাউন্ডেশন এর উপস্থিতি সকলের নজরে আসার মতন কাজ কর্মের মাধ্যমে কুষ্টিয়া সহ আসে পাশের সকল এলাকার উন্নয়ন সাধন করেছে।</h5>
                    <h5>এছাড়া মিত্র ফাউন্ডেশন কর্তৃক আয়োজিত বিভিন্ন সামাজিক অনুষ্ঠানে উপহার বিতরণ ও সমাজ উন্নয়নে মিত্র ফাউন্ডেশন ২০১৭ সাল থেকে কাজ করে আসতেসে। মিত্র ফাউন্ডেশন এর আয়োজিত বিভিন্ন সামাজিক ও কল্যান মূলক কর্মসূচি এলাকার গরিব মানুষের কাছে অনেক জনপ্রিয়। </h5>
                </div>
            </div>

            <div class="col-md-6">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <img class="d-block w-100" style="height: 90%" src="{% static 'img/one.jpg' %}" alt="First slide">
                      </div>
                      <div class="carousel-item">
                        <img class="d-block w-100" src="{% static 'img/two.jpg' %}" alt="Second slide">
                      </div>
                      <div class="carousel-item">
                        <img class="d-block w-100" src="{% static 'img/three.jpg' %}" alt="Third slide">
                      </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                    </a>
                  </div>
            </div>

        </div>
        
    </div>

    <div class="container">
      <div class="mt-5"></div>
    </div>





    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>